coaching:
    path:     /
    defaults: { _controller: "SiteNedraBundle:Coaching:index" }

coaching_show:
    path:     /{id}/show
    defaults: { _controller: "SiteNedraBundle:Coaching:show" }

coaching_new:
    path:     /new
    defaults: { _controller: "SiteNedraBundle:Coaching:new" }

coaching_create:
    path:     /create
    defaults: { _controller: "SiteNedraBundle:Coaching:create" }
    requirements: { _method: post }

coaching_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteNedraBundle:Coaching:edit" }

coaching_update:
    path:     /{id}/update
    defaults: { _controller: "SiteNedraBundle:Coaching:update" }
    requirements: { _method: post|put }

coaching_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteNedraBundle:Coaching:delete" }
    requirements: { _method: post|delete }
