news:
    path:     /
    defaults: { _controller: "SiteNedraBundle:News:index" }

news_show:
    path:     /{id}/show
    defaults: { _controller: "SiteNedraBundle:News:show" }

news_new:
    path:     /new
    defaults: { _controller: "SiteNedraBundle:News:new" }

news_create:
    path:     /create
    defaults: { _controller: "SiteNedraBundle:News:create" }
    requirements: { _method: post }

news_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteNedraBundle:News:edit" }

news_update:
    path:     /{id}/update
    defaults: { _controller: "SiteNedraBundle:News:update" }
    requirements: { _method: post|put }

news_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteNedraBundle:News:delete" }
    requirements: { _method: post|delete }
